### PR TITLE
LOG-2354: Update Dockerfile to use public base

### PR DESCRIPTION
**Pull request by jcantrill**
Update base image to be public

* https://issues.redhat.com/browse/LOG-2354

cc @alanconway

### CODE REVIEW

**Comment by syedriko** [comment]
@jcantrill are we concerned at all we're not using tags, implicit latest that is, with the new images?

**Review by alanconway — APPROVED** [review]
/lgtm

**Comment by jcantrill** [comment]
@syedriko I think we pinned it elsewhere.  Please submit a PR with changes to pin the version as needed

**Comment by jcantrill** [comment]
@syedriko I think we pinned it elsewhere.  Please submit a PR with changes to pin the version as needed

**Pull request merged**
